#!/usr/bin/env python

import sys

from freeplay_sandbox_analysis.bag import Bag
from rqt_gui.main import Main

plugin = 'freeplay_sandbox_analysis.bag.Bag'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Bag.add_arguments))
