#! /bin/bash

me=`basename "$0"`

display_usage() { 
    echo -e "Usage: $me [-h] <root of dataset>\n"
    echo -e "Count on how many frames the faces are visible\n"
    echo "  -h: display this help" 
} 


# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "h?" opt; do
    case "$opt" in
    h|\?)
        display_usage
        exit 0
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

DATASET_ROOT=$1

EXEC=$HOME/src/freeplay-sandbox-analysis/build/devel/lib/freeplay_sandbox_analysis/faces_detection

orig_path=$(pwd)

cd $DATASET_ROOT
paths=(2017**/experiment.yaml)


for ((i=0;i<${#paths[@]};i++))
do
    f=${paths[$i]}
    
    dir=$(dirname $f)
    
    if [ -f $dir/freeplay.poses.json ]; then
    
        echo "Detecting faces for experiment $f (experiment $((i+1))/${#paths[@]}..."
        $EXEC --path $dir
    
    fi
done

cd $orig_path
echo "Done"
